### ISSUE TITLE
Heap full when Ctrl-D with empty history (apparently)

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/CleanReadLine#1]
The following program gives a `Heap full` error when you press Ctrl-D:

    Start :: *World -> (String, *World)
    Start w
    # (f, w) = stdio w
    #! w = setReadLineName "Test program" w
    #! w = usingHistory w
    #! (s, w) = readLine "first prompt: " True w
    = (s, w)

But when we add

    #! w = addHistory "testentry" w

after `usingHistory` there is no such problem. Any idea?

**Comment by dopefishh** [comment]
Do you press CRTL+D in the readline prompt? Hmm, I thought I had EOFs handled correctly. I'm on it.

**Comment by dopefishh** [comment]
Fixed in `4930c9c0ddeaa5c9421d36396fd74d22db1385c6`
